-- for the weather station problems
-- https://www.infoplease.com/world/united-states-geography/latitude-and-longitude-us-and-canadian-cities

\W

use hackerrank;

insert into station (city, `state`, lat_n, long_w) values
('Albany', 'NY'             , 42  ,73      ),
('Albuquerque', 'NM'        , 35  ,106     ),
('Amarillo', 'TX'           , 35  ,101     ),
('Anchorage', 'AK'        , 61  ,149     ),
('Atlanta', 'GA'             , 33  ,84      ),
('Austin', 'TX'             , 30  ,97      ),
('Baker', 'OR'              , 44  ,117     ),
('Baltimore', 'MD'           , 39  ,76      ),
('Bangor', 'ME'            , 44  ,68      ),
('Birmingham', 'AL'         , 33  ,86      ),
('Bismarck', 'ND'           , 46  ,100     ),
('Boise', 'ID'             , 43  ,116     ),
('Boston', 'MA'            , 42  ,71      ),
('Buffalo', 'NY'            , 42  ,78      ),
('Carlsbad', 'NM'           , 32  ,104     ),
('Charleston', 'SC'         , 32  ,79      ),
('Charleston', 'WV'       , 38  ,81      ),
('Charlotte', 'NC'          , 35  ,80      ),
('Cheyenne', 'WY'           , 41  ,104     ),
('Chicago', 'IL'            , 41  ,87      ),
('Cincinnati', 'OH'         , 39  ,84      ),
('Cleveland', 'OH'          , 41  ,81      ),
('Columbia', 'SC'           , 34  ,81      ),
('Columbus', 'OH'           , 40  ,83      ),
('Dallas', 'TX'             , 32  ,96      ),
('Denver', 'CO'            , 39  ,105     ),
('Des Moines', 'IA'         , 41  ,93      ),
('Detroit', 'MI'           , 42  ,83      ),
('Dubuque', 'IA'            , 42  ,90      ),
('Duluth', 'MN'            , 46  ,92      ),
('Eastport', 'ME'          , 44  ,67      ),
('El Centro', 'CA'        , 32  ,115     ),
('El Paso', 'TX'            , 31  ,106     ),
('Eugene', 'OR'             , 44  ,123     ),
('Fargo', 'ND'              , 46  ,96      ),
('Flagstaff', 'AZ'         , 35  ,111     ),
('Fort Worth', 'TX'         , 32  ,97      ),
('Fresno', 'CA'           , 36  ,119     ),
('Grand Junction', 'CO'    , 39  ,108     ),
('Grand Rapids', 'MI'      , 42  ,85      ),
('Havre', 'MT'             , 48  ,109     ),
('Helena', 'MT'            , 46  ,112     ),
('Honolulu', 'HI'         , 21  ,157     ),
('Hot Springs', 'AR'        , 34  ,93      ),
('Houston', 'TX'            , 29  ,95      ),
('Idaho Falls', 'ID'       , 43  ,112     ),
('Indianapolis', 'IN'       , 39  ,86      ),
('Jackson', 'MS'           , 32  ,90      ),
('Jacksonville', 'FL'       , 30  ,81      ),
('Juneau', 'AK'           , 58  ,134     ),
('Kansas City', 'MO'         , 39  ,94      ),
('Key West', 'FL'           , 24  ,81      ),
('Klamath Falls', 'OR'      , 42  ,121     ),
('Knoxville', 'TN'         , 35  ,83      ),
('Las Vegas', 'NV'          , 36  ,115     ),
('Lewiston', 'ID'          , 46  ,117     ),
('Lincoln', 'NE'            , 40  ,96      ),
('Long Beach', 'CA'       , 33  ,118     ),
('Los Angeles', 'CA'      , 34  ,118     ),
('Louisville', 'KY'          , 38  ,85      ),
('Manchester', 'NH'         , 43  ,71      ),
('Memphis', 'TN'           , 35  ,90      ),
('Miami', 'FL'              , 25  ,80      ),
('Milwaukee', 'WI'          , 43  ,87      ),
('Minneapolis', 'MN'       , 44  ,93      ),
('Mobile', 'AL'             , 30  ,88      ),
('Montgomery', 'AL'         , 32  ,86      ),
('Montpelier', 'VT'          , 44  ,72      ),
('Nashville', 'TN'         , 36  ,86      ),
('Newark', 'NJ'             , 40  ,74      ),
('New Haven', 'CT'         , 41  ,72      ),
('New Orleans', 'LA'         , 29  ,90      ),
('New York', 'NY'           , 40  ,73      ),
('Nome', 'AK'             , 64  ,165     ),
('Oakland', 'CA'          , 37  ,122     ),
('Oklahoma City', 'OK'     , 35  ,97      ),
('Omaha', 'NE'              , 41  ,95      ),
('Philadelphia', 'PA'        , 39  ,75      ),
('Phoenix', 'AZ'           , 33  ,112     ),
('Pierre', 'SD'             , 44  ,100     ),
('Pittsburgh', 'PA'          , 40  ,79      ),
('Portland', 'ME'          , 43  ,70      ),
('Portland', 'OR'           , 45  ,122     ),
('Providence', 'RI'         , 41  ,71      ),
('Richfield', 'UT'          , 38  ,112     ),
('Richmond', 'VA'            , 37  ,77      ),
('Roanoke', 'VA'             , 37  ,79      ),
('Sacramento', 'CA'       , 38  ,121     ),
('Salt Lake City', 'UT'     , 40  ,111     ),
('San Antonio', 'TX'        , 29  ,98      ),
('San Diego', 'CA'        , 32  ,117     ),
('San Francisco', 'CA'    , 37  ,122     ),
('San Jose', 'CA'         , 37  ,121     ),
('San Juan', 'PR'           , 18  ,66      ),
('Santa Fe', 'NM'           , 35  ,105     ),
('Savannah', 'GA'            , 32  ,81      ),
('Seattle', 'WA'           , 47  ,122     ),
('Shreveport', 'LA'          , 32  ,93      ),
('Sioux Falls', 'SD'        , 43  ,96      ),
('Sitka', 'AK'            , 57  ,135     ),
('Spokane', 'WA'           , 47  ,117     ),
('Springfield', 'IL'        , 39  ,89      ),
('Springfield', 'MA'       , 42  ,72      ),
('Springfield', 'MO'         , 37  ,93      ),
('Syracuse', 'NY'           , 43  ,76      ),
('Tampa', 'FL'              , 27  ,82      ),
('Toledo', 'OH'             , 41  ,83      ),
('Tulsa', 'OK'             , 36  ,95      ),
('Virginia Beach', 'VA'      , 36  ,75      ),
('Washington', 'DC'         , 38  ,77      ),
('Wichita', 'KS'         , 37  ,97      ),
('Wilmington', 'NC'         , 34  ,77      )
;
